version: "3.8"
services:
  db-postgres: 
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=n_report
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - nreportapi-network

  nreportapi:
    build: ./
    depends_on:
      - db-postgres
    ports:
      - "3000:3000"
    networks:
      - nreportapi-network

networks:
  nreportapi-network:
    driver: bridge

volumes:
  postgres_data: