version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db-postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db-postgres:5432/n_report?schema=public
    volumes:
      - .:/nreportapi
      - /nreportapi/node_modules
      - ./uploads:/nreportapi/uploads

  db-postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=n_report
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: